# Site settings
title: Открытый веб
blog_title: My Territory
header-img: img/home-bg.jpg
email: mail@foma.me
copyright_name: lfoma
description: "Внеси свой вклад в развитие мира"
baseurl: "" #base url is for when the site is not at the root but at some subdirectory.
url: https://we-are.club #only used in disque comments for now
disqus_url: we-are.club # disque comments are broken if you send http:// along with url
github_username:  lfoma
facebook_username:  
stackoverflow_username: 

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
